server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1

logging:
 level:
  org.springframework.cloud.gateway: DEBUG

management:
 endpoints:
   web:
    exposure:
      include: health,info