server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: product
    password: product

  jpa:
    hibernate:
      ddl-auto: update   # dev-only: auto create/update tables
    show-sql: true       # log SQL to console

