
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productdb       # replace with real host later
    username: product
    password: product
  jpa:
    hibernate:
      ddl-auto: validate  # no schema changes in prod
    show-sql: false

# prod logging: quieter
logging:
  level:
    root: INFO
    com.techTalkEra.helloservice: INFO
