spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: product
    password: product
  jpa:
    hibernate:
      ddl-auto: update    # dev convenience
    show-sql: true        # print SQL in dev
