management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans,loggers
  endpoint:
    health:
      show-details: always
info:
  app:
    name: product-service
    version: 0.0.1
    description: CRUD API with MySQL & JPA


spring:

  datasource:
    url: jdbc:mysql://localhost:3306/productdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: product
    password: product
  jpa:
    hibernate:
      ddl-auto: update    # dev convenience
    show-sql: true        # print SQL in dev	