server:
  port: 8081

spring:
  application:
    name: PRODUCT-SERVICE
  profiles:
    active:
    - dev

# default, can be overridden per profile
logging:
  level:
    root: INFO
    com.techTalkEra.productservice: DEBUG
  file:
    name: logs/app.log




